### PR TITLE
Update pyromod patches to pyromod v3.0.1

### PR DESCRIPTION
**Pull request by usernein**
Release notes for pyromod v3: https://github.com/usernein/pyromod/releases/tag/v3.0.0

The only things i made different:
- In pyromod v3, PyromodConfig got renamed to the config object in the pyromod.config package. In AmanoTeam/pyrogram, i kept its name as PyromodConfig to avoid any confusion.
- Pyromod v3 started checking additionally for Message.message_id (to support pyrogram v1). In AmanoTeam/pyrogram it does not make sense to do that check, so i removed it.

### CODE REVIEW

**Comment by alissonlauffer** [comment]
Thanks for your contribution!

Why do the tests fail though?
Apparently there's a circular import, so maybe you could add a lazy import somewhere.

**Comment by alissonlauffer** [comment]
I've just fixed the circular imports, by lazily defining the types with strings (`"pyrogram.types.Type"`), be free to do any modifications if needed. Otherwise, I can merge the PR.

**Comment by usernein** [comment]
@alissonlauffer because i fixed it all and forgot to commit :v

**Comment by usernein** [comment]
now it's ready for merging, thank you!

**Pull request merged**
